version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=movies
      - POSTGRES_USER=movies
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always
